# Site settings
title: Chang Liu
email: cliu3@umassd.edu
description: > # this means to ignore newlines until "baseurl:"
  PhD Candidate at University of Massachusetts Dartmouth
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://changliu.co" # the base hostname & protocol for your site
twitter_username: 
github_username:  cliu3

# Build settings
markdown: kramdown

google_analytics: UA-71775586-1
show_downloads: false
theme: jekyll-theme-dinky
